### ISSUE TITLE
Project Meeting Time and Git Access

### ISSUE THREAD

**Issue by RJP43** [setriplette/golden_age#2]
Hey @setriplette @ahunker @msb81

I am opening this issue to encourage all of you to come up with a weekly/bi-weekly meeting time. You should each post your availabilities in this issue and aim for a project meeting sometime next week. 

@setriplette has likely invited each of you as a collaborator on this repo, which means you should have access to push into this repo. You should clone and practice pushing something into this repo's [sandbox](https://github.com/setriplette/golden_age/tree/master/Sandbox). Also, we created a [quick reference guide](https://github.com/ebeshero/DHClass-Hub/blob/master/Git_BasicCommands.md) on the DHClass-Hub to aid with using Git.

**Comment by ahunker** [comment]
I am only at school Monday, Wednesday, and Friday and I work all day Tuesday and Thursdays. On the days I'm at school, I'm free before and after class at 9:30-10:30 and 11:20-12:15, and later at 1:45-3:00.

**Comment by msb81** [comment]
I'm free MWF from 11:20-2, and TTH any time before 1:15.

**Comment by setriplette** [comment]
We might have to meet briefly in the half hour after class and then separately. The only time we're all "free" at the same time is the hour after class, and I almost always have meetings and class prep then. Otherwise, Madee, I think you and Audrey should meet together, because you'll be doing most of your work together, and each check back with me, Madee during our Green Scholar meeting time on Thursday, and Audrey during my office hours MWF at 2 pm. Does this work?

**Comment by setriplette** [comment]
If we need to have a major meeting we can google hangout.

**Comment by setriplette** [comment]
Oh and Madee, please accept my invite to be a collaborator.
